#!/usr/bin/env python3
"""
Generate member-specific embedded HTML files from FocusBoard templates.
No fetch calls, all data embedded as JavaScript constants.
"""

import os
import json
from pathlib import Path

def main():
    # Define paths
    base_dir = Path(__file__).parent.resolve()
    data_dir = base_dir / 'data'
    dist_dir = base_dir / 'dist'
    static_dir = base_dir / 'static'

    # Create dist directory
    dist_dir.mkdir(exist_ok=True)

    # Read source data and files
    with open(data_dir / 'members.json', 'r', encoding='utf-8') as f:
        members_data = json.load(f)

    with open(data_dir / 'projects.json', 'r', encoding='utf-8') as f:
        projects_data = json.load(f)

    with open(static_dir / 'css' / 'style.css', 'r', encoding='utf-8') as f:
        style_css = f.read()

    with open(static_dir / 'js' / 'utils.js', 'r', encoding='utf-8') as f:
        utils_js = f.read()

    with open(static_dir / 'js' / 'confetti.js', 'r', encoding='utf-8') as f:
        confetti_js = f.read()

    with open(static_dir / 'js' / 'index.js', 'r', encoding='utf-8') as f:
        index_js = f.read()

    with open(base_dir / 'index.html', 'r', encoding='utf-8') as f:
        index_html = f.read()

    # For each member, generate an HTML file
    for member in members_data.get('members', []):
        member_id = member['id']

        # Filter projects for this member
        member_projects = projects_data.copy()
        member_projects['projects'] = [
            p for p in projects_data.get('projects', [])
            if member_id in p.get('members', [])
        ]

        # Create embedded data as JavaScript
        embedded_member_id = f"""const EMBEDDED_MEMBER_ID = "{member_id}";"""

        embedded_members = f"""const EMBEDDED_MEMBERS_DATA = {json.dumps(members_data, ensure_ascii=False, indent=2)};"""

        embedded_projects = f"""const EMBEDDED_PROJECTS_DATA = {json.dumps(member_projects, ensure_ascii=False, indent=2)};"""

        # Modify index.js to use EMBEDDED_MEMBER_ID as fallback
        modified_index_js = index_js.replace(
            "  const params   = new URLSearchParams(window.location.search);\n  const memberId = params.get('member');",
            "  const memberId = \n    new URLSearchParams(window.location.search).get('member') \n    || EMBEDDED_MEMBER_ID;"
        )

        # Read firebase-config
        with open(static_dir / 'js' / 'firebase-config.js', 'r', encoding='utf-8') as f:
            firebase_js = f.read()

        # Build the full HTML
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>FocusBoard — Open Source Edition</title>
  <style>
{style_css}
  </style>
  <script src="https://www.gstatic.com/firebasejs/10.8.0/firebase-app-compat.js"></script>
  <script src="https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore-compat.js"></script>
</head>
<body class="page">

  <!-- Header -->
  <header class="header">
    <span class="header__logo">📋 FocusBoard</span>
    <span class="header__meta" id="week-label">2025-W12</span>
  </header>

  <main class="page__body container">

    <!-- Announcement Banner (shown if available) -->
    <div class="banner" id="announcement-banner" style="display:none;"></div>

    <!-- Page Title -->
    <h1 style="font-size:18px; font-weight:600; margin-bottom:24px;">
      This Week's Update
      <span style="font-size:13px; font-weight:400; color:var(--text-secondary); margin-left:8px;" id="member-name"></span>
    </h1>

    <!-- Project Sections (auto-generated by JS) -->
    <div id="projects-container"></div>

    <hr class="divider">

    <!-- Submit All Button -->
    <button class="btn btn--primary btn--full btn--lg" id="btn-submit">
      Submit All →
    </button>

  </main>

  <script>
{embedded_member_id}

{embedded_members}

{embedded_projects}

{firebase_js}

{utils_js}

{confetti_js}

// Override fetchJSON (defined in utils.js) with embedded data
async function fetchJSON(path) {{
  if (path.includes('members.json')) return EMBEDDED_MEMBERS_DATA;
  if (path.includes('projects.json')) return EMBEDDED_PROJECTS_DATA;
  if (path.includes('announcements.json')) return [];
  throw new Error('Unknown path: ' + path);
}}

{modified_index_js}
  </script>
</body>
</html>
"""

        # Write to dist/[member_id].html
        output_file = dist_dir / f"{member_id}.html"
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(html_content)

        print(f"✓ Generated: {output_file}")

    print(f"\n✅ Done! Generated {len(members_data.get('members', []))} HTML files in {dist_dir}")

if __name__ == '__main__':
    main()
